apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: email-operator-system
  name: email-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["emails.mailerlite.com"]
    resources: ["emails", "emailsenderconfigs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["emails.mailerlite.com"]
    resources: ["emails/status"]
    verbs: ["get", "update", "patch"]
